### ISSUE TITLE
No way to dictate display order for news items, presentations, etc.

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#1]
## Story
When I enter news items or presentations in contentful, they display in the order I enter them - last created or edited at the top of the page.  This is regardless of the historic published date or the presentation date.  Additionally, and more importantly, if you edit a previously publish post it moves it back up to the top ("most recent") regardless of its original placement.  There seems to be no way to reorder them.  So in order to migrate old news and presentations to the new site, the only way for them to appear in order on https://samvera.github.io/hyku-next/news is to enter the oldest first moving to most recent last.

**Note:**  This isn't urgent, just a nice-to-have.  We won't be migrating content often.
**Workaround:**  You can dictate the order by unpublishing all news items entered, then publishing them again in the order you want to display them.  This is no more work than any other UI for arranging publication order, just takes some figuring out.  Ideally, News would be dictated by Publish Date.

## Acceptance
- [x] News items display by Publish Date, most recent at the top
- [x] Presentations display by Date, most recent at top
- [ ] OR: Admin has the ability to rearrange the display order of news items and presentations

**Comment by adamjarling** [comment]
@DraxIndustries79 This should now be wrapped up, automatically filtering by Publish Date, descending in the UI code.
