### ISSUE TITLE
"Get Started" homepage button goes nowhere

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#11]
## Story
Currently the "Get Started" button on the homepage goes to an error page.
<img width="973" alt="Screenshot 2024-05-29 at 8 20 52 AM" src="https://github.com/samvera/hyku-next/assets/37004183/0d4e145c-52d8-42f6-8178-f97ab23c5f40">

## Acceptance
- [x] Get Started button at https://samvera.github.io/hyku-next/ goes somewhere (maybe https://github.com/samvera/hyku, but Learn More already goes there too...)

**Comment by adamjarling** [comment]
Wrapping this one up
