### ISSUE TITLE
Contact Page Content

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#12]
https://samvera.github.io/hyku-next/contact
<img width="1252" alt="Screenshot 2024-05-29 at 10 22 11 AM" src="https://github.com/samvera/hyku-next/assets/37004183/d80dcda3-2133-47eb-bd79-33ce6f484ee8">

## Get in touch
As part of the Samvera Community, Hyku is driven by the participation of users and developers.  There are many ways to contribute, collaborate, or just get some questions answered as you get started with Hyku.

[Email Us](info@samvera.org)
With questions, requests for demos, and other communications.

## Collaborate (note, there's currently a typo here "Collborate" on the site)
[Hyku Interest Group](https://samvera.atlassian.net/wiki/spaces/samvera/pages/419533203/Samvera+Hyku+Interest+Group)
An open and welcoming forum to find out what is in development for Hyku and to connect with users with similar needs.

## Developers
Have a PR to contribute?  https://github.com/samvera/hyku

## Hosted Solutions
[HykuUP](https://hykuup.com/) by SoftServ by Scientist.com
[Ubiquity Repositories](https://ubiquity.pub/repositories/) by Ubiquity Press

[Service Providers page](https://samvera.org/the-community/service-providers)
For hosted solutions, Requests for Proposals, or contracted work

## Slack
[Samvera Slack](https://samvera.atlassian.net/wiki/spaces/samvera/pages/405211682/Getting+Started+in+the+Samvera+Community#Join-the-Samvera-Slack-workspace)
Request to join Samvera's slack workspace and join the #hyku channel.  Introduce yourself and ask questions!

**Comment by adamjarling** [comment]
@DraxIndustries79 I ended up pushing the Hosted Solutions to it's own content section as it's feeling a little heavy, and maybe more important.  It's currently on the homepage.  Curious on thoughts?

**Comment by DraxIndustries79** [comment]
@adamjarling I'm Ok with this, but I also never mind having SoftServ's hosted service on the homepage (self-interest).  It's the obvious doens't-fit for "Contact" page.  Objectively, it might fit better on Getting Started?

**Comment by adamjarling** [comment]
@DraxIndustries79 Ok, yea seems like it makes sense on Getting Started
