### ISSUE TITLE
Footer Links Don't Work

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#3]
## Story
The links in the header menu work fine but the same links in the footer go to an error page.  The urls appear to be missing "hyku-next".  For instance:

Correct URL:  https://samvera.github.io/hyku-next/news; https://samvera.github.io/hyku-next/getting-started
Footer Routes to:  https://samvera.github.io/news; https://samvera.github.io/getting-started

**Footer:**
![Screenshot 2024-05-28 at 8 59 36 AM](https://github.com/samvera/hyku-next/assets/37004183/248890ea-5522-4710-a6a6-c64224c10305)

**Error Page:**
![Screenshot 2024-05-28 at 9 01 23 AM](https://github.com/samvera/hyku-next/assets/37004183/daf3a9ce-ebcb-4431-ac2f-101faf29076e)

## Acceptance
- [x] Footer links successfully route to the same urls that the header links route to

**Comment by adamjarling** [comment]
Wrapping up now
