### ISSUE TITLE
"Online" toggle for Presentations displays incorrect status (Remove)

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#4]
## Story
I confess, I'm not sure what the "Online" yes/no option refers to in Presentations.  It's either meant to show or hide this entry on the site, or means that the presentation itself is available online.  Either way, it doesn't work.  It shows "Online" as green regardless of selecting yes, no, or leaving unchecked.  I also don't think it's particularly useful and would vote for removing.

**The radio button in the Presentations creation UI:**
<img width="181" alt="Screenshot 2024-05-28 at 7 34 30 PM" src="https://github.com/samvera/hyku-next/assets/37004183/75f11b06-111d-4294-9d17-10be9465842e">

**How it displays on https://samvera.github.io/hyku-next/presentations:**
<img width="268" alt="Screenshot 2024-05-28 at 7 34 10 PM" src="https://github.com/samvera/hyku-next/assets/37004183/61a948f1-d61e-48f1-af10-6dcb30bfff7d">

## Acceptance
- [ ] "Online" is hidden so it doesn't appear on the site regardless of status, OR:
- [ ] "Online" works properly and shows green if Yes is checked, presumably red if No is checked (Not sure what "No" is meant to display)

**Comment by adamjarling** [comment]
@DraxIndustries79 Ha, yea that is the intent.  I can do either, wire it up so Green if the presentation is online, and have the little thing not appear at all if not online.   Or I can just scrap the element all together.  Your call?

**Comment by adamjarling** [comment]
This is updated to only show the green button if the conference "Online" is set to `true` in Contentful for an individual Presentation.
