### ISSUE TITLE
Reorder Features (Or give access to edit them)

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#5]
## Story
The features on https://samvera.github.io/hyku-next/features list the release information from oldest (top) to newest (bottom).  Reverse order would be better, so the newest information is always added to the top.
<img width="978" alt="Screenshot 2024-05-29 at 7 38 14 AM" src="https://github.com/samvera/hyku-next/assets/37004183/7545c421-de9c-4e50-8cfb-933f45e18f1e">

## Acceptance
- [ ] Features are reorganized on a timeline of most recent at top, OR:
- [x] Share information with Kevin on how to edit https://samvera.github.io/hyku-next/features

**Comment by adamjarling** [comment]
@DraxIndustries79 Features is now in Contentful.  I manually updated the ordering of the Hyku releases (for now)
