### ISSUE TITLE
Need ability for line breaks in WYSIWYG (Features & Implementations)

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#6]
## Story
At least in Features and Implementations > Implementations, I cannot seem to make a line break in Contentful.  Markdown doesn't work, it just renders the marks on the page.  Example, Brian's information is entered on different lines but renders on one line on the page.  Two returns creates a break, but also adds a space.

**How it's entered in Contentful:**
![Screenshot 2024-05-29 at 7 48 08 AM](https://github.com/samvera/hyku-next/assets/37004183/406adb35-2244-43c6-9113-c6f3c4ec86ed)

**How it renders on https://samvera.github.io/hyku-next/features:**
<img width="546" alt="Screenshot 2024-05-29 at 7 50 26 AM" src="https://github.com/samvera/hyku-next/assets/37004183/7951dd04-55d2-408d-abd6-96bfc4b413f5">

## Acceptance
- [x] There's a way to do a line return in Contentful.

**Comment by adamjarling** [comment]
@DraxIndustries79 Fixing this now
