### ISSUE TITLE
Presentations Page Content

### ISSUE THREAD

**Issue by DraxIndustries79** [samvera/hyku-next#9]
## Presentations and Demos
In addition to the archived presentation below, useful Hyku feature demos can be found on YouTube.
- Visit the official [Hyku YouTube Channel](https://www.youtube.com/channel/UC_m1Ovaaasa2ksyGaqz5i0Q/)
- Visit the original [Hydra-in-a-Box YouTube Channel](https://www.youtube.com/channel/UC1eopKtm-k_f93RTfzHSvMQ) for early demos (2015-2017)

**Comment by adamjarling** [comment]
Wrapping this one up
